### ISSUE TITLE
캘린더 구현

### ISSUE THREAD

**Issue by NanaYoungg** [NanaYoungg/FamStory#6]

**Comment by choing98** [comment]
구현한 기능
  1. 인터페이스로 데이터전달 => 데이터 읽어오기 구현
  2.  xml부분 레이아웃 수정 
당장 추가해야될기능
  1. 비어있는데이터는 ViewMoreText 부분 inflater로 가리기
  2. 이미 데이터가 있을경우 추가버튼 가리고 삭제,수정버튼만 표시

**Comment by choing98** [comment]
구현한 기능
- [ 비어있는데이터는 ViewMoreText 부분 inflater로 가리기 ] 
- [ 이미 데이터가 있을경우 추가버튼 가리고 삭제,수정버튼만 표시] 

수정 및 추가해야되는 기능

- [주석,변수명 최적화 ] 
- [Calendar setOnDateChange 가 일어났을때 파이어베이스 DB에서 날짜값  바로 가져오기] 
- [삭제기능, 수정기능 구현]
